Client created
Traceback (most recent call last):
  File "d:\OneDrive - LTTS\Desktop\waste\main.py", line 36, in <module>
    node.set_attribute(ua.AttributeIds.Value, ua.DataValue(value))
  File "C:\Users\40020507\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\opcua\common\node.py", line 263, in set_attribute
    result[0].check()
  File "C:\Users\40020507\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\opcua\ua\uatypes.py", line 218, in check
    raise UaStatusCodeError(self.value)
opcua.ua.uaerrors._auto.BadNotWritable: "The access level does not allow writing to the Node."(BadNotWritable)
Data change from server:
Exception calling data change handler
Traceback (most recent call last):
  File "C:\Users\40020507\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\opcua\common\subscription.py", line 153, in _call_datachange
    self._handler.datachange_notification(data.node, item.Value.Value.Value, event_data)
  File "d:\OneDrive - LTTS\Desktop\waste\main.py", line 16, in datachange_notification
    value = val.Value
AttributeError: 'float' object has no attribute 'Value'
Exception calling data change handler
Traceback (most recent call last):
  File "C:\Users\40020507\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\opcua\common\subscription.py", line 153, in _call_datachange
    self._handler.datachange_notification(data.node, item.Value.Value.Value, event_data)
  File "d:\OneDrive - LTTS\Desktop\waste\main.py", line 16, in datachange_notification
    value = val.Value
AttributeError: 'float' object has no attribute 'Value'
Exception calling data change handler
Traceback (most recent call last):
  File "C:\Users\40020507\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\opcua\common\subscription.py", line 153, in _call_datachange
    self._handler.datachange_notification(data.node, item.Value.Value.Value, event_data)
  File "d:\OneDrive - LTTS\Desktop\waste\main.py", line 16, in datachange_notification
    value = val.Value
AttributeError: 'float' object has no attribute 'Value'
Exception calling data change handler
Traceback (most recent call last):
  File "C:\Users\40020507\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\opcua\common\subscription.py", line 153, in _call_datachange
    self._handler.datachange_notification(data.node, item.Value.Value.Value, event_data)
  File "d:\OneDrive - LTTS\Desktop\waste\main.py", line 16, in datachange_notification
    value = val.Value
AttributeError: 'float' object has no attribute 'Value'
Exception calling data change handler
Traceback (most recent call last):
  File "C:\Users\40020507\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\opcua\common\subscription.py", line 153, in _call_datachange
    self._handler.datachange_notification(data.node, item.Value.Value.Value, event_data)
  File "d:\OneDrive - LTTS\Desktop\waste\main.py", line 16, in datachange_notification
    value = val.Value
AttributeError: 'float' object has no attribute 'Value'
Exception calling data change handler
Traceback (most recent call last):
  File "C:\Users\40020507\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\opcua\common\subscription.py", line 153, in _call_datachange
    self._handler.datachange_notification(data.node, item.Value.Value.Value, event_data)
  File "d:\OneDrive - LTTS\Desktop\waste\main.py", line 16, in datachange_notification
    value = val.Value
AttributeError: 'float' object has no attribute 'Value'
